crim-ca/weaver

README.rst

Updated README before distribution

---

docs/source/conf.py
requirements-docs.txt

fix https://github.com/huard/sphinx-autodoc-pywps/pull/1

use pywps integrated api docs

---

.github/workflows/secret-scan.yml
CHANGES.rst
Makefile
README.rst
docs/source/conf.py
tests/functional/test_builtin.py
weaver/datatype.py
weaver/owsexceptions.py
weaver/processes/builtin/jsonarray2netcdf.py
weaver/processes/wps_package.py
weaver/store/mongodb.py
weaver/utils.py
weaver/wps_restapi/processes/processes.py

- fix failing job update using invalid status location
- add more logging for application job process (more steps progress)
- avoid losing job logs when collecting internal wps process logs 
- allow process `jsonarray2netcdf` to fetch a remote file

improve job execution

---

CHANGES.rst
weaver/wps_restapi/processes/processes.py

- DescribeProcess
- GetCapabilities

Add wps languages for other wps requests types

---

.github/workflows/secret-scan.yml

- remove redundant and over verbose (generates issues) secrets-scan action

update to github actions

---

CHANGES.rst
requirements-dev.txt
requirements.txt
tests/functional/test_builtin.py
tests/processes/test_wps_package.py
tests/test_formats.py
tests/test_utils.py
tests/utils.py
weaver/formats.py
weaver/processes/builtin/__init__.py
weaver/processes/builtin/jsonarray2netcdf.py
weaver/processes/opensearch.py
weaver/processes/wps_package.py
weaver/utils.py
weaver/wps_restapi/jobs/jobs.py

- improve and reuse the common request/retry function to handle potential temp failures
- improve mime-type parsing to consider extra parameters and extended supported ones

retry reuse + mime-type handling

---

CHANGES.rst
tests/functional/test_ems_end2end.py
tests/test_formats.py
tests/test_utils.py
weaver/processes/wps_package.py
weaver/utils.py
weaver/wps_restapi/processes/processes.py

few patches during testing to handle sporadic request failures

retry-request for functional tests and fetching remote package reference

---

CHANGES.rst
docs/source/conf.py
tests/functional/test_ems_end2end.py
tests/processes/test_wps_package.py
weaver/datatype.py
weaver/processes/wps_package.py
weaver/status.py
weaver/typedefs.py

fix io type direct

---

.travis.yml
CHANGES.rst
Makefile
config/weaver.ini.example
docker/Dockerfile-base
requirements-dev.txt
requirements.txt
setup.cfg
tests/functional/test_wps_app.py
tests/processes/test_wps_package.py
tests/test_formats.py
tests/test_utils.py
tests/travis-ci/docker-compose.smoke-test.yml
weaver/__init__.py
weaver/app.py
weaver/config.py
weaver/formats.py
weaver/processes/utils.py
weaver/processes/wps_package.py
weaver/processes/wps_workflow.py
weaver/utils.py
weaver/wps_restapi/api.py
weaver/wps_restapi/colander_extras.py
weaver/wps_restapi/processes/processes.py
weaver/wps_restapi/quotation/__init__.py
weaver/wps_restapi/swagger_definitions.py

- add smoke test of built docker images to make sure they can boot
- move `main` to `weaver.app` to limit chances of import error caused by easily misplaced package imports not yet installed during setup

smoke test docker

---

requirements-dev.txt

- resolve 'security' flag of older pylint

fix pylint requirement to use latest

---

docs/source/processes.rst

patch docs as originally intended in #183, possible future change with #184

patch docs 

---

.github/labeler-files.yml
.github/labeler-words.yml

Update labeler-words and labeler-files

---

.pylintrc
requirements-dev.txt
tests/processes/test_convert.py
tests/wps_restapi/test_jobs.py
weaver/database/__init__.py
weaver/processes/wps_package.py
weaver/status.py

target pylint 2.7 with appropriate changes

Pylint update

---

.github/workflows/tests.yml
CHANGES.rst
weaver/processes/utils.py

- Ensure that configuration file definitions specified in ``processes`` and ``providers`` will override older database
definitions respectively matched by ``id`` and ``name`` when starting `Weaver` if other parameters were modified.

WPS load config

---

CHANGES.rst
tests/functional/utils.py
tests/utils.py
weaver/datatype.py
weaver/processes/convert.py
weaver/processes/execution.py
weaver/processes/utils.py
weaver/processes/wps1_process.py
weaver/processes/wps_package.py
weaver/processes/wps_process_base.py
weaver/wps/utils.py
weaver/wps_restapi/processes/processes.py
weaver/wps_restapi/providers/providers.py

Employs a common generator of `WebProcessingService` client to apply requests options in a more consistent way.

add get_wps_client function with request options

---

CHANGES.rst
tests/functional/test_builtin.py
tests/wps_restapi/test_processes.py
weaver/datatype.py

Default execution mode reported in process job control options (fixes #248)

Added async-execute as default execution mode in process job control options

---

CHANGES.rst
docs/source/references.rst
weaver/wps_restapi/api.py

update metadata doc links

---

.dockerignore
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.gitignore
.remarkignore
.remarkrc
.stylelintrc.json
Makefile
README.rst
docs/_static/custom.css

- fix codacy integration with CRIM organization
- fix markdown issues flagged by codacy using new markdown linting makefile targets

fix codacy badge in readme + add markdown linting 

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE/pull-request-template.md
.remarkrc
Makefile

- add pr template
- update issue templates
- remove problematic markdown title annotated by label anyway

update github templates

---

CHANGES.rst
weaver/datatype.py

Better support of datatype field/attr/property auto-resolution from getitem/getattr for access via dict key or class property.
Taken out of pending #261 to use it within other pending PRs.

adjust datatype auto-resolution of fields

---

CHANGES.rst
tests/functional/test_builtin.py
tests/functional/test_wps_package.py
tests/test_opensearch.py
tests/wps_restapi/test_processes.py
weaver/datatype.py
weaver/processes/convert.py
weaver/wps_restapi/swagger_definitions.py

Add missing process I/O field details as per (opengeospatial/ogcapi-processes@748bba6) (addresses #211)

Add missing process I/O field details (fixes #211)

---

CHANGES.rst
weaver/database/base.py
weaver/database/mongodb.py

improve typing of db store to provide expected auto-complete per store implementation

db store typing

---

Makefile
requirements-dev.txt
requirements.txt

closes https://github.com/crim-ca/weaver/pull/366

deps security check + ignore pyup celery

---

CHANGES.rst
requirements.txt
weaver/database/mongodb.py

resolve issue identified in [#382 (comment)](https://github.com/crim-ca/weaver/pull/382/#issuecomment-993922679)

pin pymongo<4 (relates to #386)

---

LICENSE.txt
weaver/__meta__.py
weaver/wps_restapi/api.py

add license and many other service related rel links to landing page 

---

README.rst

- add more recent updates
- add ogc-apps pilot demo videos 
- fixes #194
- fixes #204

update readme 

---

CHANGES.rst
requirements.txt
tests/functional/test_cli.py
tests/functional/test_vault.py
tests/test_vault.py
weaver/cli.py
weaver/datatype.py
weaver/processes/wps_package.py
weaver/vault/utils.py
weaver/vault/views.py

Temporarily secure the vault file to avoid plain text contents.

vault file encryption

---

README.rst

Apply some updates to link to recent technical reports and OGC API schema related to Weaver developments.

Update README best practices

---

CHANGES.rst
weaver/cli.py

fix error introduced in https://github.com/crim-ca/weaver/pull/411

fix cli deploy headers

---

CHANGES.rst
weaver/wps/utils.py

set pywps server url using resolved WPS location with weaver settings

---

.github/workflows/tests.yml
Makefile
setup.cfg

see https://github.com/codecov/codecov-action\#%EF%B8%8F--deprecation-of-v1

switch codecov uploader

---

CHANGES.rst
tests/functional/test_cli.py
tests/resources/__init__.py
tests/resources/wps_colibri_flyingpigeon_subset_storage.json
tests/test_datatype.py
tests/test_formats.py
weaver/cli.py
weaver/datatype.py
weaver/formats.py
weaver/processes/constants.py
weaver/processes/convert.py
weaver/utils.py

- fix non-OAS schema reference in I/O
- format Media-Type from OpenGIStypes 
- resolution of CLI process info with OLD/OGC schemas

bugfixes of geo-related operations and testing wps/oas handling

---

.github/workflows/secret-scan.yml

relate to https://github.com/gitleaks/gitleaks-action/issues/57

pin gitleaks to fix test workflow 

---

tests/wps_restapi/test_api.py

relates to https://github.com/opengeospatial/NamingAuthority/issues/183

patch broken test due to opengis schema reference missing content-type header

---

CHANGES.rst
requirements.txt
tests/wps_restapi/test_providers.py

relates to https://github.com/geopython/OWSLib/pull/794

bump owslib==0.26.0 to retrieve WPS remote provider fixes

---

CHANGES.rst
requirements.txt

fix owslib/pyproj for Python 3.10 (fixes #459)

---

.github/workflows/greetings.yml

relates to https://github.com/actions/first-interaction/issues/101

patch greetings action failing workflow

---

requirements-dev.txt
requirements-doc.txt
requirements-sys.txt
requirements.txt

SNYK-PYTHON-SETUPTOOLS-3113904 
closes #497 
closes #498
closes #499
closes #501

fix minimal version of setuptools 

---

CHANGES.rst
Makefile
tests/wps_restapi/test_jobs.py
tests/wps_restapi/test_providers.py
weaver/compat.py
weaver/processes/utils.py
weaver/typedefs.py
weaver/utils.py
weaver/wps_restapi/processes/utils.py
weaver/wps_restapi/swagger_definitions.py

flagged by more recent version of `pylint`

switch `distutils.version.LooseVersion` to `packaging.version.Version`

---

README.rst

Relates to https://github.com/badges/shields/issues/8671

fix GitHub CI badge URL

---

CHANGES.rst
setup.cfg
tests/__init__.py
tests/functional/test_wps_package.py
tests/processes/test_utils.py
tests/test_cli.py
tests/utils.py
tests/wps/test_utils.py
tests/wps_restapi/test_api.py
tests/wps_restapi/test_processes.py
tests/wps_restapi/test_providers.py
weaver/formats.py
weaver/owsexceptions.py
weaver/processes/execution.py
weaver/typedefs.py
weaver/wps/utils.py

- ignore expected warnings by weaver configuration for tests
- resolve warning issues with appropriate solutions

fix warnings

---

requirements.txt

- https://app.snyk.io/org/fmigneault/project/e70ab783-8025-473e-9f7c-3b18a705d514#issue-SNYK-PYTHON-NUMPY-2321970
- https://app.snyk.io/org/fmigneault/project/e70ab783-8025-473e-9f7c-3b18a705d514#issue-SNYK-PYTHON-NUMPY-2321964
- https://app.snyk.io/org/fmigneault/project/e70ab783-8025-473e-9f7c-3b18a705d514#issue-SNYK-PYTHON-NUMPY-2321966

fix numpy vulnerabilities for supported python versions

---

docs/source/conf.py

relates to https://github.com/sphinx-doc/sphinx/issues/12030
relates to https://github.com/orgs/sphinx-doc/discussions/12032

let sphinx pick a more recent user-agent for docs linkcheck

---

CHANGES.rst
weaver/wps_restapi/swagger_definitions.py

relates to https://github.com/common-workflow-language/cwl-v1.2/issues/278

fix older CWL v1.2.1 schema reference 

---

CHANGES.rst
requirements.txt

security fix for werkzeug

---

CHANGES.rst
config/weaver.ini.example
docs/source/configuration.rst
tests/functional/application-packages/EchoOptional/deploy.yml
tests/functional/application-packages/EchoOptional/package.cwl
tests/functional/application-packages/WorkflowEchoOptional/deploy.yml
tests/functional/application-packages/WorkflowEchoOptional/execute.yml
tests/functional/application-packages/WorkflowEchoOptional/package.cwl
tests/functional/test_workflow.py
weaver/processes/execution.py
weaver/processes/wps_package.py
weaver/processes/wps_workflow.py
weaver/wps/utils.py

fixes https://crim-ca.atlassian.net/browse/GD-559

fix output ID resolution + add wps size config

---

requirements.txt

Relates to https://github.com/numpy/numpy/issues/26781

pin `numpy<2` for Python <3.10

---

README.rst

- relates to https://github.com/bird-house/birdhouse-docs/pull/58
- relates to https://github.com/bird-house/birdhouse-docs/pull/59
- relates to https://github.com/Ouranosinc/pavics-sdi/pull/331

add PAVICS Ouranos server reference to Weaver

---

README.rst

update readme keywords + update readme jupyter notebook docs

---

.github/workflows/tests.yml
Makefile

https://docs.codecov.com/docs/test-analytics

add junit codecov update for flaky test analysis 

---

CHANGES.rst
docs/source/package.rst
tests/processes/test_wps_package.py
weaver/processes/wps_package.py

fix metadta role as URI + add WPS->CWL metadata inverse mapping

---

tests/test_cli.py
weaver/cli.py

fix CLI test inconsistently failing by request mock

---

Makefile
requirements-dev.txt

- add test profiling utility to analyse speedup opportunities 
- define …make run_test function to centralize definition

test profiling tools

---

requirements.txt

- relates to https://github.com/shapely/shapely/issues/2212 
Problem identified in RTD build: ❌ https://readthedocs.org/projects/pavics-weaver/builds/27026552/
Testing resolution (this PR) in: ✅ https://readthedocs.org/projects/pavics-weaver/builds/27033825/

patch fix against unresolved GEOS library by shapely 

---

.github/workflows/zenodo.yml

- relates to https://github.com/rseng/zenodo-release/pull/17

use description HTML file as-is for zenodo publish github action

---

CHANGES.rst
requirements.txt

CVE-2023-50782, CVE-2024-6119, CVE-2024-26130, CVE-2023-49083

update cryptography to fix CVEs

---

README.rst
docs/source/conf.py

- fixes #595
- fixes #736 
- fixes #738 
- relates to #735
- relates to #812

add references for OSPD, OGC TB-20, CWLcon2021 and ESIP video resources 

---

requirements-dev.txt

- relates to https://github.com/pyupio/safety/issues/711

pin marshmallow to resolve safety dependency error during 'check' call

---

CHANGES.rst
weaver/wps_restapi/jobs/jobs.py

Fix provider job html

---

README.rst
docs/source/conf.py

add OGC Testbed-20 reports and 131st members meeting references 
