- requirements.txt
require beta version minimum of yaml until they fix and release 4.2/5.1 versions
> pyyaml requirement

- custom.cfg.example
- requirements.txt
- weaver/wps_restapi/jobs/notify.py
- weaver/wps_restapi/processes/processes.py
- We can now send emails using gmail, or any other email provider.
- Login only occurs when a password is provided in the configuration.
- The notification email is removed from the logs, for privacy reasons.
> Send emails using any smtp address

- tests/wps_restapi/test_processes.py
- weaver/datatype.py
- weaver/store/mongodb.py
- weaver/wps_restapi/processes/processes.py
- weaver/wps_restapi/swagger_definitions.py
Support the `Accept-Language` header when executing a WPS process, match it to the best-supported language (according to the GetCapabilities call) and forward it to `owslib.wps.WebProcessingService`.
Fixes #73 
Requires https://github.com/geopython/OWSLib/pull/655 and https://github.com/geopython/OWSLib/pull/654 to be released in the next owslib version. This PR shouldn't break anything in the meantime, it just doesn't do anything.
> Wps execute accept language

- weaver/wps_restapi/processes/processes.py
- Could be None when updating weaver
- The serialized string must be empty when no accept-language header is provided
> fix for accept_language when empty or None

- CHANGES.rst
- tests/wps_restapi/test_processes.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/processes/processes.py
For example, an input of `{"id": "test", "data": "2020"}`
was cast to `{"id": "test", "data": 2020.0}`
because `DataFloat` is the first item in `weaver.wps_restapi.swagger_definitions.ValueType`
> Don't cast values when validating a job's POST body

- CHANGES.rst
- tests/functional/test_builtin.py
- tests/functional/test_ems_end2end.py
- tests/utils.py
- tests/wps_restapi/test_jobs.py
- weaver/processes/builtin/__init__.py
- weaver/processes/builtin/jsonarray2netcdf.py
- weaver/processes/utils.py
- weaver/processes/wps_package.py
- weaver/typedefs.py
- weaver/utils.py
- weaver/wps.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/processes/processes.py
- patch `builtin` process execution failing since cwltool 2.x update
- return `data` result if WPS had a literal output (was assuming only reference file)
- address PyPWS URLHandler which was making a an invalid href because `input.data` was called instead of `input.url` and/or `input.file` as needed
- prepare the field for eventual #91 fix when addressed in geopython/pywps#526
@f-PLT  @MatProv 
Inviting you to follow releases since weaver execution might/will start to impact you through finch for climate services/processes, or other future projects.
> Fix builtin process job execution and results href

- CHANGES.rst
- setup.cfg
old for example : 
https://pavics-weaver.readthedocs.io/en/1.5.0/ 
compared to how it will look like now:
with each link pointing to the correct issue/tag
> changelog links to github tags and issues

- CHANGES.rst
- weaver/processes/utils.py
- weaver/processes/wps_package.py
- weaver/wps_restapi/processes/processes.py
- Fixes incorrect parsing of JSON output as 'multiple-output' because of new job location that now stores a relative path to file (relates to #25)
- Add more execution log in to saved job logs adding the captured stderr & stdout of the underlying docker app or script.
comparison examples:  
[no-capture.log](https://github.com/crim-ca/weaver/files/4613378/no-capture.log)
[with-capture.log](https://github.com/crim-ca/weaver/files/4613382/with-capture.log)
> Json output + job captured logging

- .github/labeler-words.yml
- .travis.yml
- Makefile
- tests/travis-ci/custom.cfg
Use travis stages for early failure of linter checks before batch tests with job/env/matrix.
Also, travis will mark success build earlier if all required tests are passed regardless of optional ones.
Before we had to open the "Python 3.7"  test which was running linters and look through the whole log to check if this was the cause of failure. This specific test was also very long as it ran many extras.
Failing use cases will also be more clearly highlighted per-version, per-os and per-test subset.
> improving travis-ci test sequence with staged error reports

- CHANGES.rst
- config/weaver.ini.example
- requirements.txt
- weaver/wps.py
- add ``weaver.wps_workdir`` config to set where fetched tmp files will be written to during WPS process execution
- fix yaml requirements for python 2
> pywps workdir

- setup.cfg
Some files (most importantly `weaver/utils.py`) were lost during report/calculation of coverage on codecov.io (https://community.codecov.io/t/missing-files-in-codecov-but-not-in-report/825) when source/root is `./weaver`. Others where generating inconsistent coverage values (eg: `weaver/datatype.py`). This fixes both issues.
For some reason, most files where found automatically, but only some listed here where not handled correctly: 
https://codecov.io/gh/crim-ca/weaver/pull/160/changes
> fix source path of coverage report to avoid losing some files

- .github/workflows/issue-labeler.yml
- CHANGES.rst
- Makefile
- config/weaver.ini.example
- docs/source/conf.py
- tests/functional/test_wps_package.py
- tests/processes/test_wps_package.py
- tests/test_formats.py
- weaver/database/base.py
- weaver/database/mongodb.py
- weaver/datatype.py
- weaver/formats.py
- weaver/processes/wps_package.py
- weaver/tweens.py
- weaver/wps.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/processes/processes.py
- weaver/wps_restapi/swagger_definitions.py
- extend features of PR #150 using `weaver.wps_workdir` 
- better setup cwltool tmpdir and results location
- functional with docker-sibling setup
- fixes incorrect reference when default type parsing is used (introduced by PR #128)
- addresses #155 [experimental] with user/group applied to cwl app & readonly inputs
- avoid reload pywps configs every time
- better setup of cwltool logs according to the rest of the app log level
- map wps-outputs with job uuid to pywps uuid to make it easier to identify matching items
> config workdir and type handling

- CHANGES.rst
@MatProv 
I find the changes introduced in #176 to be a bit too ambitious to be merged as is into master with already many unversioned changes.  So I pushed a `1.11.0` version at the commit just prior to all the ones from #176. 
I also find that such massive change are still quite lacking in term of changelog.
Can you please summarize all changes applied within that PR under the `Unreleased` section?
After this, we will immediately add another tag `1.12.0`.
> add minor version prior to esgf merge

- CHANGES.rst
- weaver/processes/wps_workflow.py
Create an ``stdout.log`` or ``stderr.log`` file in case ``cwltool`` hasn't created it
> Fix missing log files

- CHANGES.rst
- Makefile
- README.rst
- config/wps_processes.yml.example
- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/faq.rst
- docs/source/installation.rst
- docs/source/package.rst
- docs/source/processes.rst
- docs/source/references.rst
- requirements-dev.txt
- requirements-sys.txt
- tests/functional/test_wps_package.py
- weaver/processes/builtin/jsonarray2netcdf.py
- weaver/processes/builtin/metalink2netcdf.py
- weaver/processes/utils.py
- weaver/store/mongodb.py
- weaver/wps_restapi/processes/processes.py
- weaver/wps_restapi/providers/providers.py
- weaver/wps_restapi/swagger_definitions.py
- add parsing of `providers` entries in `wps_processes.yml`
- align remote/dynamic provider processes response with local/static processes 
(under `"processes"` key instead of flat list)
Usefull for upcoming birdhouse-deploy integration with existing WPS providers in the stack
> config remote providers

- CHANGES.rst
- weaver/datatype.py
- weaver/processes/execution.py
- weaver/processes/wps_package.py
fixes #90
Job execution logs side-by-side comparison of before/after changes. 
Instead of reporting same (final) percent all the time and status `failed`/`succeeded` accordingly to final result, reports `running` (which was the status of the job at the time they were logged) and make percent proportionally increase. 
Sadly, reported progress/status is still limited to how verbose the package is *during* its execution - and collected after the fact to apply to the job log, but they are more consistent with what happened otherwise.
> fix job log reporting with gradual progress completion

- CHANGES.rst
- weaver/store/mongodb.py
Previous PRs (#223 [[smoke-test error](https://github.com/crim-ca/weaver/runs/2016670675)], #225 [[smoke-test ok](https://github.com/crim-ca/weaver/runs/2018397147)], #226 [[smoke-test ok](https://github.com/crim-ca/weaver/runs/2017330325)]) illustrated during `smoke-test` that sometimes race conditions happens during `builtin` process registration. 
This PR adds more specific validation of existing processes against new ones to register and catches/ignores situations were the error can be safely discarded.
> improve handling race condition of duplicate builtin process registration

- CHANGES.rst
- tests/utils.py
- tests/wps/test_utils.py
- tests/wps_restapi/test_jobs.py
- tests/wps_restapi/test_processes.py
- weaver/utils.py
- weaver/wps/utils.py
- weaver/wps_restapi/processes/processes.py
wps-client creation caching control according to beaker config and request headers
Avoids re-querying the full process listing and client object such that multiple calls of `/providers/x/processes/y`, `/providers/x/processes/z`, etc. will only do an initial `getcapabilites`, and will reuse the object for subsequent `describeprocess` operation until the cache expires or is enforced with no-cache.
> wps-client cached

- CHANGES.rst
- tests/functional/test_wps_package.py
- tests/wps_restapi/test_colander_extras.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/swagger_definitions.py
fix invalid Not keyword resolution for `LiteralInputType` which resulted into too verbose process description inputs
The missing deserialization of the resulting mapping following OpenAPI `not` keyword validation resulted into all fields under a literal input type to bubble up in the process description. For example, fields like `data_format`, `mode`, `mimetype`, `workdir`, etc. that come from the pywps/owslib/cwl object json conversion would be returned.
> fix invalid Not keyword resolution 

- requirements-dev.txt
relates to https://github.com/PyCQA/astroid/issues/1017
errors raised by false positives: 
https://github.com/crim-ca/weaver/runs/2776250383?check_suite_focus=true#step:8:295
> pin astroid<2.5.8 that triggers pylint false positives 

- CHANGES.rst
- tests/test_datatype.py
- tests/wps_restapi/test_processes.py
- weaver/datatype.py
support pre-deployed processes that did not provide jobControlOptions by providing the default value `["async-execute"]`
> fix missing jobControlOptions in pre-deployed processes

- Makefile
- setup.cfg
- weaver/datatype.py
- weaver/processes/wps_workflow.py
- weaver/store/mongodb.py
- weaver/wps/service.py
- weaver/wps_restapi/colander_extras.py
This is a *hack* around issue described in https://github.com/PyCQA/pycodestyle/issues/996
> Address `fix-lint` target problem not respecting ignore comments

- CHANGES.rst
- tests/functional/test_wps_package.py
- tests/wps_restapi/test_processes.py
- weaver/datatype.py
Fixing representation of `maxoccurs` and `minoccurs` according to ogcapi (fixes #263).
>  Fixed  representation according to ogcapi (fixes #263)

- tests/functional/test_wps_package.py
- tests/json_examples/opensearch_deploy.cwl
- tests/json_examples/opensearch_deploy.json
- tests/test_opensearch.py
Update the `cwl` payloads that are running directly in `weaver`, to avoid any dysfunction when the security [issue](https://www.crim.ca/jira/browse/DAC-437) will be fixed.
> Fixed cwl running environment to prevent dysfunctions for next cwl patch

- .gitignore
- CHANGES.rst
- tests/functional/test_wps_package.py
- weaver/processes/execution.py
- weaver/wps_restapi/swagger_definitions.py
Execute request with inline values and arrays under mapping according to [OGC-API](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/execute.yaml)
> Execute request with inline values and arrays under mapping (fixes #265)

- CHANGES.rst
- tests/functional/test_wps_package.py
- tests/wps_restapi/test_jobs.py
- weaver/processes/execution.py
Add missing processID and providerID details in job status info response as per opengeospatial/ogcapi-processes#234 (fixes #270)
> Add missing processID and providerID details in job status info response

- CHANGES.rst
- weaver/wps/utils.py
Replace explicit `deepcopy()` call by basic `dict()` copy from conversion of input headers in `get_wps_client` has `EnvironHeaders` instance raises serialize error with TextIO field with `deepcopy()`.
> fix get_wps_client headers copy - serialize error

- CHANGES.rst
- weaver/store/mongodb.py
add upsert/replace operation instead of insert during builtin process initial registration
Fixes #246
> avoid DuplicateKeyError during initial builtin process registration

- .github/workflows/tests.yml
- tests/functional/test_wps_package.py
- run '<test-case>-only' variants to avoid useless re-check/install of pre-installed dependencies when applicable
- skip package setup when running workflow docker smoke test
> improvements to dependency installs during test workflow

- CHANGES.rst
- requirements.txt
- tests/functional/test_wps_package.py
- weaver/processes/utils.py
- weaver/processes/wps_package.py
Explicitly block unsupported and `builtin` process type during deployment from the API.
> Block unknown process type deployment (fixes #276)

- weaver/wps_restapi/swagger_definitions.py
fix circular import between `swagger_definitions` and `wps_restapi.utils` 
introduced in https://github.com/crim-ca/weaver/commit/76abd6e30c302ba06a272ac9dd648fdbbd752206
> fix ciruclar import

- CHANGES.rst
- tests/wps_restapi/test_colander_extras.py
- tests/wps_restapi/test_processes.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/swagger_definitions.py
Fix Execute inputs incorrectly formatted not validated/raised as invalid due to optional inputs permitted for some processes.
> Fix Execute inputs validation while still allow as optional

- tests/test_opensearch.py
decommission OpenSearch endpoint tests that are not available anymore 
(employed during TestBed-14, but not evaluated for a while)
> decommission unavailable OpenSearch endpoint

- CHANGES.rst
- config/weaver.ini.example
- docs/source/appendix.rst
- docs/source/configuration.rst
- docs/source/processes.rst
- docs/source/tutorial.rst
- tests/functional/test_wps_package.py
- tests/utils.py
- tests/wps/test_utils.py
- weaver/datatype.py
- weaver/processes/execution.py
- weaver/processes/wps_package.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/typedefs.py
- weaver/utils.py
- weaver/wps/service.py
- weaver/wps/utils.py
- weaver/wps_restapi/swagger_definitions.py
- Support contextual WPS output location using ``X-WPS-Output-Context`` header to store ``Job`` results.
When a ``Job`` is executed by providing this header with a sub-directory, the resulting outputs of the ``Job``
will be placed and reported under the corresponding location relative to WPS outputs (path and URL).
- Replace ``Job.execute_async`` getter/setter by simple property using more generic ``Job.execution_mode``
for storage in database. Provide ``Job.execute_async`` and ``Job.execute_sync`` properties based on stored mode.
- Simplify ``execute_process`` function executed by `Celery` task into sub-step functions where applicable.
- Simplify forwarding of ``Job`` parameters between ``PyWPS`` service ``WorkerService.execute_job`` method
and `Celery` task instantiating it by reusing …
> Job output context + Job execution improvements

- CHANGES.rst
- docs/source/references.rst
- tests/wps_restapi/test_jobs.py
- weaver/datatype.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/swagger_definitions.py
- support Job `type` and `processID` filter queries (relates to #268)
- provide Job status type field (resolves #351) 
- increase OGC conformance (relates to #53, #231)
> improve conformance with OGC for job metadata and search

- .github/workflows/tests.yml
- CHANGES.rst
- docker/docker-compose.yml.example
- docs/source/installation.rst
- docs/source/references.rst
- requirements.txt
- tests/wps_restapi/test_jobs.py
- weaver/datatype.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/utils.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/swagger_definitions.py
- resolve #268 
- enforce `mongo==5.0` to used improved search
- improve job search function by separating filters into distinct methods and extendable pipeline 
Depends on https://github.com/crim-ca/weaver/pull/355 for part of the job search refactoring
> Job min max duration

- tests/utils.py
- weaver/database/base.py
- weaver/database/mongodb.py
- weaver/datatype.py
- weaver/processes/builtin/__init__.py
- weaver/store/mongodb.py
- weaver/utils.py
Fix incorrect use of `*` characters in typing that are supposed to refer to "one of the values" args and kwargs can take.
> fix typings

- requirements.txt
pyup flags `celery` as out of date (#366)
While it is true, the corresponding tests in that PR are all failing due to missing package version `5.2.x`.
Since this is not critical, temporarily mark it as ignored to avoid recurrent issues from pyup and runners to test for nothing. 
This can be addressed at a later date when more critical component of `celery` are updated, such as in #348
> add pyup ignore celery in requirements

- CHANGES.rst
- docs/source/processes.rst
- docs/source/references.rst
- tests/functional/test_wps_package.py
- tests/test_utils.py
- tests/utils.py
- tests/wps/test_utils.py
- weaver/processes/constants.py
- weaver/processes/wps_package.py
- weaver/utils.py
- weaver/wps/utils.py
- Add handling of ``Content-Disposition`` header providing preferred ``filename`` or ``filename*`` parameters when
fetching file references instead of the last URL fragment employed by default
(resolves `#364 <https://github.com/crim-ca/weaver/issues/364>`_).
- Add more security validation of the obtained file name from HTTP reference, whether generated from URL path fragment
or other header specification.
> Fix file content disposition

- CHANGES.rst
- tests/functional/test_wps_package.py
- tests/processes/test_convert.py
- tests/processes/test_wps_package.py
- weaver/processes/convert.py
- weaver/processes/opensearch.py
- weaver/processes/sources.py
- weaver/processes/wps_package.py
- weaver/typedefs.py
- weaver/wps_restapi/swagger_definitions.py
- Fix resolution of `WPS` I/O provided as mapping instead of listing during deployment in order to properly parse
them and merge their metadata with corresponding `CWL` I/O definitions.
- Fix `DataSource` and `OpenSearch` typing definitions to more rapidly detect incorrect data structures during parsing.
> Fix deploy io dict

- CHANGES.rst
- tests/functional/test_docker_app.py
- tests/functional/test_wps_package.py
- tests/wps_restapi/test_jobs.py
- tests/wps_restapi/test_processes.py
- tests/wps_restapi/test_status_codes.py
- weaver/app.py
- weaver/database/mongodb.py
- weaver/datatype.py
- weaver/exceptions.py
- weaver/processes/execution.py
- weaver/processes/utils.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/typedefs.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/examples/job_not_found.json
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/swagger_definitions.py
- add db revision operations
- replace str UUID-like field in db to actual UUID object
- resolve issue parsing unspecified UUID format
With the addition of `X-Auth-Docker` header, an UUID was stored as-is. 
With more recent versions of `pymongo`, the unspecified representation type directly raises when reading the object.
> resolve UUID db handling

- docs/source/conf.py
workaround https://github.com/ashb/sphinx-argparse/issues/7
> disable set_type_checking_flag since comments are used anyway

- CHANGES.rst
- docs/source/conf.py
- weaver/cli.py
- Fix help message of CLI arguments not properly grouped within intended sections.
- Fix handling of mutually exclusive CLI arguments in distinct operation sub-parsers.
- Fix requirement of ``--process`` and ``--job`` CLI arguments.
> fix CLI arguments

- CHANGES.rst
- tests/functional/test_cli.py
- weaver/cli.py
- add support of JSON-like string as input to CLI --body and --cwl options of deploy operation
- fix previous ``--process`` enforced requirement invalid during  ``deploy`` if provided via ``--body``
> CLI JSON-like body and CWL parameters

- README.rst
- docs/Makefile
Provide similar (external) representation of youtube videos with link in readme displayed on Github since embedded iframe doesn't work in repo (still works in ReadTheDocs).
(pseudo image/link video)
(real embedded video)
> Update README.rst to provide YouTube embedded-like view on GitHub

- CHANGES.rst
- setup.cfg
add explicit release number labels in changelog to facilitate url anchor referencing without dates
> rst changelog anchors for releases 

- CHANGES.rst
- docs/source/references.rst
- tests/functional/test_cli.py
- tests/functional/test_workflow.py
- tests/functional/test_wps_package.py
- tests/functional/utils.py
- tests/wps_restapi/test_processes.py
- weaver/processes/convert.py
- weaver/processes/execution.py
- weaver/processes/wps_package.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/constants.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/swagger_definitions.py
Better support 'type' field for file 'href' input & other link/metadata references.
- Add ``schema`` query parameter to ``GET /jobs/{jobID}/outputs`` request allowing to select between ``OGC``, ``OLD``
``OGC+strict`` and ``OLD+strict`` representations (case insensitive), each with different combinations
of ``format.mimeType``, ``format.mediaType`` and/or directly ``type`` field to provide the Content-Type of an
output with ``href`` file.
By default, both the ``format`` (i.e.: ``OLD`` schema) and the ``type`` (i.e.: ``OGC`` schema) are simultaneously
reported for backward and forward compatibility, and for `OGC` compliance to return a file reference IANA Media-Type
(resolves `#401 <https://github.com/crim-ca/weaver/issues/401>`_).
- Add support of ``type`` as alias to the Media-Type of the …
> better support 'type' field for file 'href' input & link/metadata

- CHANGES.rst
- weaver/typedefs.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/constants.py
- weaver/wps_restapi/swagger_definitions.py
- conformance API can return references by `category` 
- add CWL / OGC-Best-Practices EO App Pkg conformance items
relates to:
- #56
- #103 
- #105 
- #294
- #399)
> API conformance references by category and OGC Best Practices

- CHANGES.rst
- docs/source/processes.rst
- tests/wps_restapi/test_jobs.py
- weaver/datatype.py
- weaver/formats.py
- weaver/typedefs.py
- weaver/utils.py
- weaver/wps_restapi/jobs/jobs.py
- Add support of ``Accept`` header, ``f`` and ``format`` request queries for ``GET /jobs/{jobID}/logs`` retrieval
using ``text``, ``json``, ``yaml`` and ``xml`` (and their corresponding Media-Type definitions) to list `Job` logs.
> support different accept header / format query for job logs listing

- CHANGES.rst
- tests/wps_restapi/test_processes.py
- weaver/cli.py
- weaver/datatype.py
- weaver/processes/utils.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/swagger_definitions.py
- Add `deploymentProfile` (see requirement https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/deploy_replace_undeploy/standard/requirements/ogcapppkg/REQ_profile-docker.adoc) using available `type` parameter that provided similar information.
- Remove ``deploymentProfileName`` requirement during `Process` deployment. The corresponding ``deploymentProfile``
property is instead automatically generated from resolved `CWL` package/reference or remote `WPS` reference. This
further simplifies deployment using the `CLI` to its bare minimum components as only the `CWL` or `WPS` reference
needs to be provided along the desired `Process` ID without any further details.
- fixes #319
> deploymentProfileName optional + profile deploymentProfile in process description

- CHANGES.rst
- tests/processes/test_convert.py
- tests/test_cli.py
- tests/utils.py
- weaver/cli.py
- weaver/processes/convert.py
- weaver/wps_restapi/swagger_definitions.py
In was impossible up until now to specify which *supported format* to employ when providing a file reference to a process that allows many. This PR fixes this problem with more parsing. The selected `@` is inspired of what is used by WPS for KVP specification of the same definitions.
> support CLI inputs with extra parameters for mediaType + more CLI tests

- weaver/processes/convert.py
move any2cwl_io literal warning outside of call to avoid misleading message when expected no-match
> adjust confusion warn log message

- CHANGES.rst
- docs/source/configuration.rst
- requirements.txt
- tests/functional/test_vault.py
- tests/resources/__init__.py
- tests/test_utils.py
- tests/utils.py
- tests/wps_restapi/test_api.py
- tests/wps_restapi/test_jobs.py
- tests/wps_restapi/test_providers.py
- weaver/cli.py
- weaver/datatype.py
- weaver/exceptions.py
- weaver/processes/constants.py
- weaver/processes/execution.py
- weaver/processes/wps_package.py
- weaver/quotation/estimation.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/typedefs.py
- weaver/utils.py
- weaver/wps_restapi/examples/job_statistics.json
- weaver/wps_restapi/jobs/__init__.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/jobs/utils.py
- weaver/wps_restapi/swagger_definitions.py
- add runtime options to allow resource monitoring (as best as possible, relates to #138)
- add additional resource monitoring using the `celery` process itself and `psutil`
- fix invalid job URL `Location` header duplicated in response, causing errors during CLI tests using it
> Resource monitoring and statistics

- .pylintrc
- CHANGES.rst
- tests/functional/test_cli.py
- tests/wps_restapi/test_processes.py
- weaver/cli.py
- Fix `CLI` not allowing expected combination of ``--username`` and ``--password`` for Docker authentication when
deploying a `Process` that needs it to retrieve the referenced repository and image in its `CWL` definition.
> fix cli docker username/password/token args resolution

- CHANGES.rst
- tests/functional/test_cli.py
- tests/functional/utils.py
- tests/processes/test_utils.py
- tests/resources/__init__.py
- tests/wps_restapi/test_jobs.py
- weaver/cli.py
- weaver/formats.py
- weaver/processes/execution.py
- weaver/processes/utils.py
- weaver/status.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/utils.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/swagger_definitions.py
Changes:
--------
- Add `CLI` and `WeaverClient` support of ``logs``, ``exceptions`` and ``statistics`` retrieval.
- Add `CLI` and `WeaverClient` support of `Job` search filtered by ``tags``, ``process`` and ``providers`` queries.
- Add `CLI` and `WeaverClient` support of `Job` search filtered by multiple ``status`` values.
Fixes:
------
- Fix ``tags`` query parameter not applied to filter `Job` search requests.
> add CLI/WeaverClient job retrieval operations

- CHANGES.rst
- weaver/processes/wps_package.py
- weaver/wps/service.py
- weaver/wps/storage.py
- weaver/wps/utils.py
- Fix ``weaver.wps_output_context`` sub-directory resolved from default settings or ``X-WPS-Output-Context`` request
header not employed for storing the `XML` status location and `Job` log files next to the `Job` outputs directory.
> fix wps-output-context not used for wps xml status and job log files

- .github/workflows/tests.yml
- requirements.txt
Since the dependency is not needed anymore, we can reduce the test worker setup time as well as the resulting docker image.
Relates to #459
> remove pyproj with owslib==0.27.2

- CHANGES.rst
- tests/utils.py
- weaver/processes/builtin/__init__.py
- weaver/processes/wps_package.py
- Add more explicit ``PackageException`` error messages with contextual details when a `CWL` file reference cannot be
resolved correctly.
- Ensure all generated test-webapps use the same test database collection.
Fixes:
------
- Fix resolution of `CWL` file from references that do not provide a known ``Content-Type`` that can represent `CWL`
contents. This can occur when deploying a ``builtin`` `Process` from the local file reference, which does not generate
a request and, therefore, no ``Content-Type``. This can occur also for servers that incorrectly or simply do not
report their response ``Content-Type`` header.
- Fix resolution of file reference with explicit `CWL` or `YAML` extensions when ``Content-Type`` is not reported or is
indicated as ``plain/text``.
- Fix invalid resolution of …
> fixes for test execution

- CHANGES.rst
- requirements.txt
Workaround `json2xml` limiting deps for latest `certifi`, `requests`, `urllib3` versions.
Relates to https://github.com/vinitkumar/json2xml/issues/157 (strict dependencies enforced by package)
Relates to https://github.com/meanmail-dev/requirements/issues/95 (parsing requirements in PyCharm)
> workaround json2xml limiting deps

- requirements-dev.txt
relates to https://github.com/spulec/moto/issues/5341
> pin moto>=4.0.8.dev17 to fix werkzeug>=2.2.2 dependency

- requirements-dev.txt
Relates to https://github.com/spulec/moto/issues/5341
> Pin released `moto>=4.0.8`

- CHANGES.rst
- tests/wps_restapi/test_api.py
- tests/wps_restapi/test_jobs.py
- weaver/formats.py
- weaver/typedefs.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/swagger_definitions.py
Changes:
--------
- Return ``Content-Type: application/vnd.oai.openapi+json; version=3.0`` for OpenAPI endpoint response referenced
by ``service-desc`` in the API conformance details, as specified by [OGC API - Processes - OpenAPI 3.0 requirement class](https://docs.ogc.org/is/18-062r2/18-062r2.html#toc43).
- Support the generation of external schema references (``$ref``) using the ``schema_ref`` attribute if provided
in a ``colander.SchemaNode`` that does not provide an explicit object schema definition with properties.
- Add Python typing definitions related to OpenAPI specification.
Fixes:
------
- Fix invalid generation of OpenAPI 3.0 specification for `Weaver` API using ``cornice_swagger``.
The generated schema structure used to return a mix of Swagger 2.0 and OpenAPI 3.0 …
> fix OpenAPI Spec generation from cornice-swagger with 3.x schema

- setup.cfg
- weaver/processes/wps_package.py
There are many instances of `PackageException`-derived errors that are explicitly raised in the code for preemptively handling the detection of invalid conditions. The purpose of those errors raised explicitly is to provide better messages or contextual information than generic/uncaught builtin errors that would occur somewhere later in the code. All of those instances are intended to generally stop the execution at that point, and then be gracefully handled by the API. 
Given this context, raised `PackageException` are not all explicitly unit-tested, since evaluating each edge case error is tedious to set up and can easily change over time. In order to focus more on the "important code", we ignore those explicitly raised errors and assume the error they flag are simply to avoid further …
> mark all explicitly raised PackageException as ignored by coverage

- CHANGES.rst
- requirements.txt
- fixes #386
- relates to celery/celery#7834
- relates to celery/kombu#1536
> fix kombu requirement for pymongo>=4 under celery

- CHANGES.rst
- tests/wps_restapi/test_processes.py
- weaver/processes/constants.py
- weaver/wps_restapi/swagger_definitions.py
- Support `CWL` definition for ``cwltool:CUDARequirement`` to request the use of a GPU, including support for using
Docker with a GPU.
- Support `CWL` definition for ``NetworkAccess`` to indicate whether a process requires outgoing IPv4/IPv6 network
access.
Fixes #104
> Include additional cwl requirements

- CHANGES.rst
- requirements-dev.txt
- requirements.txt
- tests/functional/test_cli.py
- tests/wps_restapi/test_api.py
- tests/wps_restapi/test_colander_extras.py
- weaver/datatype.py
- weaver/processes/convert.py
- weaver/processes/sources.py
- weaver/processes/wps_package.py
- weaver/status.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/swagger_definitions.py
- Fix dynamic regex definitions for schema validation with ``colander>=2`` that modifies ``URL_REGEX`` pattern
(relates to https://github.com/Pylons/colander/pull/352).
> fix dynamic regex definitions for schema validation with `colander>=2`

- CHANGES.rst
- requirements-doc.txt
- pin sphinx_autodoc_typehints[type_comment]>=1.19 to resolve missing extras requirement (relates to https://github.com/tox-dev/sphinx-autodoc-typehints/issues/263)
> pin sphinx_autodoc_typehints[type_comment]>=1.19

- CHANGES.rst
- tests/processes/test_convert.py
- weaver/processes/convert.py
Initial problem was found while trying to execute a process through the CLI, using in it's inputs an array of three or more elements all using the same input ID.
The problem was isolated to the `convert_input_values_schema` function.
Under the OGC schema, when building the list for repeated IDs, the function simply added the previous list to a new list:
```
input_prev = input_dict[input_id]
input_dict[input_id] = [input_prev, input_data]
```
Trying to add to `input_dict` a second element worked fine, but when adding a third, the result became `[[input_prev], input_date]`
Added a small check to convert `input_prev` if not already a list and switched to an append function.
Tests were adjusted to include lists of more than 2 elements and everything seems alright.
Also tested with my initial …
> Fix `convert_input_values_schema` for multiple values

- requirements.txt
Relates to https://github.com/KipCrossing/geotiff/pull/59
> fix zarr requirement under geotiff required by pywps

- tests/functional/application-packages/CatalogSearch/package.cwl
- weaver/wps_restapi/swagger_definitions.py
- fix minor JSON schema titles causing invalid ref definition names
- JSON formatting
> fix minor JSON schema titles causing invalid ref definition names

- .pylintrc
- CHANGES.rst
- README.rst
- requirements-dev.txt
- tests/functional/test_cli.py
- tests/functional/test_docker_app.py
- tests/test_schemas.py
- tests/test_utils.py
- tests/wps_restapi/test_api.py
- tests/wps_restapi/test_jobs.py
- tests/wps_restapi/test_processes.py
- weaver/datatype.py
- weaver/processes/utils.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/swagger_definitions.py
- Add the official `CWL` `JSON` schema reference
(https://github.com/common-workflow-language/cwl-v1.2/pull/256)
as ``$schema`` parameter returned in under the `OpenAPI` schema for the `CWL` component employed by `Weaver`
(fixes #547).
- Add ``$schema`` field auto-insertion into the generated `OpenAPI` schema definition by ``CorniceSwagger`` when
corresponding ``colander.SchemaNode`` definitions contain a ``_schema = "<URL>"`` attribute (fixes #157).
> add $schema OpenAPI references and apply official CWL JSON schema reference

- docker/docker-compose.yml.example
- remove deprecated chmod command for older mongodb in example docker-compose
- adjust networks
closes #296
> update example docker-compose

- CHANGES.rst
- weaver/wps_restapi/providers/providers.py
- weaver/wps_restapi/swagger_definitions.py
- weaver/wps_restapi/utils.py
- Fix ``GET /providers/{provider_id}`` response using ``$schema`` instead of ``$id`` to provide its content schema.
relates to #551
> fix rendering of provider schema reference in response body 

- CHANGES.rst
- tests/functional/test_wps_app.py
- tests/test_owsexceptions.py
- tests/wps_restapi/test_processes.py
- weaver/processes/convert.py
- weaver/store/mongodb.py
- weaver/utils.py
- weaver/wps_restapi/swagger_definitions.py
- Fix `Job` creation failing when submitting an empty string as input for a `Process` that allows it due
to schema validation incorrectly preventing it.
> fix schema validation prohibiting job execution with empty string input

- CHANGES.rst
- tests/utils.py
- tests/wps_restapi/test_processes.py
- tests/wps_restapi/test_providers.py
- weaver/processes/utils.py
- weaver/processes/wps_package.py
- weaver/store/mongodb.py
-  Fix ``get_sane_name`` checks performed on `Process` ID and `Service` name to use ``min_len=1`` in order to allow
valid `WPS` process definition on existing servers to resolve references that are shorter than the previous default
of 3 characters.
> allow `get_sane_name` check for process/service ID to be shorter to accommodate existing WPS servers

- .github/workflows/tests.yml
- CHANGES.rst
- Makefile
- docker/Dockerfile-base
- setup.cfg
- tests/smoke/docker-compose.smoke-test.yml
- tests/smoke/tests/run_tests.sh
- tests/smoke/tests/test_cwl_nodejs.py
- Fix missing Node.js requirement in built Docker image in order to evaluate definitions that employ
`CWL` ``InlineJavascriptRequirement``, such as ``valueFrom`` employed for numeric ``Enum`` input type validation.
> add smoke tests scripts to evaluate node.js dependency within built docker image

- CHANGES.rst
- tests/functional/test_cli.py
- tests/functional/utils.py
- weaver/cli.py
- weaver/datatype.py
- weaver/processes/utils.py
- weaver/wps_restapi/providers/__init__.py
- weaver/wps_restapi/providers/providers.py
- weaver/wps_restapi/swagger_definitions.py
- Add ``GET /providers/{provider_id}/processes/{process_id}/package`` endpoint that allows retrieval of the `CWL`
`Application Package` definition generated for the specific `Provider`'s `Process` definition.
- Add `CLI` ``package`` operation to request the remote `Provider` or local `Process` `CWL` `Application Package`.
- Add `CLI` output reporting of performed HTTP requests details when using the ``--debug/-d`` option.
- Modify default behavior of ``visibility`` field (under ``processDescription`` or ``processDescription.process``)
to employ the expected functionality by native `OGC API - Processes` clients that do not support this option
(i.e.: ``public`` by default), and to align resolution strategy with deployments by direct `CWL` payload which do not
include this feature either. A …
> add CLI package operation + support CWL package retrieval for provider process

- requirements-dev.txt
relates to https://github.com/edaniszewski/pylint-quotes/issues/29
> pin `pylint<3` to avoid `ImportError` in `pylint-quotes`

- CHANGES.rst
- tests/functional/test_cli.py
- weaver/cli.py
- Add `CLI` ``execute`` options ``--output-public/-oP`` and ``--output-context/-oC OUTPUT_CONTEXT`` that add the
specified ``X-WPS-Output-Context`` header to request the relevant output storage location of `Job` results.
- resolves https://crim-ca.atlassian.net/browse/DAC-190
- relates to https://github.com/bird-house/birdhouse-deploy/pull/388
> add CLI options --output-public and --output-context to set X-WPS-Output-Context header easily

- CHANGES.rst
- config/weaver.ini.example
- tests/test_notify.py
- tests/wps_restapi/test_jobs.py
- weaver/datatype.py
- weaver/notify.py
- weaver/processes/execution.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/swagger_definitions.py
- Add utility methods for `Job` to easily retrieve its various URLs.
- Add ``weaver.wps_email_notify_timeout`` setting (default 10s) to avoid SMTP server deadlock on failing connection.
- Modify the ``encrypt_email`` function to use an alternate strategy allowing ``decrypt_email`` on `Job` completed.
- Remove ``notification_email`` from ``GET /jobs`` query parameters.
Due to the nature of the encryption strategy, this cannot be supported anymore.
- Fix `Job` submitted with a ``notification_email`` not reversible from its encrypted value to retrieve the original
email on `Job` completion to send the notification (fixes #568).
- Fix example Mako Template for email notification using an unavailable property ``${logs}``.
Instead, the new utility methods ``job.[...]_url`` should be used to …
> fix notification email encrypt/decrypt implementation

- CHANGES.rst
- docs/source/cli.rst
- docs/source/configuration.rst
- docs/source/processes.rst
- docs/source/references.rst
- tests/functional/test_cli.py
- tests/test_cli.py
- tests/test_notify.py
- weaver/cli.py
- weaver/datatype.py
- weaver/notify.py
- weaver/processes/execution.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/typedefs.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/jobs/utils.py
- weaver/wps_restapi/swagger_definitions.py
- weaver/wps_restapi/templates/notification_email_example.mako
- Add `Job` ``subscribers`` support to define `OGC`-compliant callback URLs where HTTP(S) requests will be sent upon
reaching certain `Job` status milestones (fixes #230).
- Add email notification support to the new ``subscribers`` definition (extension over `OGC` minimal requirements).
- Deprecate `Job` ``notification_email`` in the `OpenAPI` specification in favor of ``subscribers``, but preserve
parsing of its value if provided in the `JSON` body during `Job` submission for backward compatibility support of
existing servers. The ``Job.notification_email`` attribute is removed to avoid duplicate references.
- Add notification email for `Job` ``started`` status, only available through the ``subscribers`` property.
- Add ``{PROCESS_ID}/{STATUS}.mako`` template detection under the …
> support callback request subscribers and job notification refactoring

- CHANGES.rst
- tests/functional/test_docker_app.py
- tests/wps_restapi/test_colander_extras.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/colander_extras.py
- weaver/wps_restapi/swagger_definitions.py
- Add schema validation and reference to the `API` landing page, with additional parameters to respect `OGC` schema.
- Add multiple `JSON` schema references for schema classes that are represented by corresponding `OGC` definitions.
- Fix auto-insertion of ``$schema`` and ``$id`` URI references into `JSON` schema and their data content representation.
When in `OpenAPI` context, schemas now correctly report their ``$id`` as the reference schema they represent (usually
from external `OGC` schema references), and ``$schema`` as the `JSON` meta-schema. When representing `JSON` data
contents validated against a `JSON` schema, the ``$schema`` property is used instead to refer to that schema.
All auto-insertions of these references can be enabled or disabled with options depending on what is …
> fix schema references and properties in rendered JSON schema/contents

- CHANGES.rst
- tests/wps_restapi/test_processes.py
- weaver/processes/utils.py
- weaver/typedefs.py
- weaver/wps_restapi/swagger_definitions.py
- Support alternative representations from `OGC API - Processes` schemas for ``executionUnit`` definition
during `Process` deployment. The *unit* does not need to be nested under ``unit`` or a list anymore, and can instead
be directly provided as `JSON` mapping. For backward compatibility, the previous list representation is still allowed
(fixes #507).
- Support an additional ``type`` property along a ``unit`` item describing an ``executionUnit`` to specify an IANA
Media-Type that categories the ``unit`` contents, similarly to how it could be provided for its ``href`` counterpart.
For the moment, only `CWL`-based ``unit`` are supported, but this could allow future extensions to provide alternate
representations of an `Application Package`.
> add alternative executionUnit formats to support OGC-API schemas

- CHANGES.rst
- weaver/datatype.py
- weaver/wps_restapi/api.py
- weaver/wps_restapi/processes/processes.py
- weaver/wps_restapi/swagger_definitions.py
- Add ``alternate`` references, as ``Link`` header and within the `JSON` content ``links`` property when applicable, in
the returned `Process` description response to refer between the `XML` and the corresponding `JSON` representations.
- Fix inconsistent or missing schema references to updated `OGC` schema locations, and align their based URL locations
for corresponding ``/conformance`` endpoint reporting.
> update conformance links, schema references, and align reqs with OGC locations

- CHANGES.rst
- tests/functional/test_builtin.py
- weaver/processes/builtin/file_index_selector.py
- weaver/processes/builtin/jsonarray2netcdf.py
- weaver/processes/builtin/metalink2netcdf.cwl
- weaver/processes/builtin/metalink2netcdf.py
- weaver/xml_util.py
- Add more tests to validate core code paths of ``builtin`` `Process` ``jsonarray2netcdf``, ``metalink2netcdf`` and
``file_index_selector`` with validation of happy path and error handling conditions.
- Fix invalid parsing of `XML` Metalink files in ``metalink2netcdf``. Metalink V3 and V4 will now properly consider the
namespace and specific content structure to extract the NetCDF URL reference, and the `Process` will validate that the
extracted reference respects the NetCDF extension.
> add tests and fixes to validate builtin processes core script

- CHANGES.rst
- requirements-dev.txt
- requirements.txt
- tests/test_utils.py
- weaver/typedefs.py
- weaver/utils.py
- weaver/wps/service.py
- Closes #581
- Closes #582
- Closes #584
- Closes #585
- Relates to https://github.com/pallets/werkzeug/issues/2710
> use `werkzeug>=3.0.1` to resolve security vulnerability

- CHANGES.rst
- tests/functional/test_wps_app.py
- weaver/formats.py
- weaver/wps/service.py
Fixes
- Fix default `XML` format resolution for `WPS` endpoint when no ``Accept`` header or ``format``/``f`` query parameter
is provided and that the request is submitted from a Web Browser, which involves additional control logic to select
the applicable ``Content-Type`` for the response.
Browser WPS XML response auto-redirected to JSON caused an unresolved process description when submitted from the browser.
> fix browser WPS XML response content-type resolution

- CHANGES.rst
- config/weaver.ini.example
- docs/source/configuration.rst
- tests/wps/test_utils.py
- weaver/utils.py
- weaver/wps/utils.py
- Add ``weaver.wps_client_headers_filter`` setting that allows filtering of specific `WPS` request headers from the
incoming request to be passed down to the `WPS` client employed to interact with the `WPS` provider.
- fixes #600
> add `weaver.wps_client_headers_filter` setting to filter WPS provider headers

- AUTHORS.rst
- CHANGES.rst
- docs/source/cli.rst
- tests/test_cli.py
- weaver/cli.py
Add `weaver.cli.SessionAuthHandler` class which uses the cookies stored in a pre-existing `requests.Session` instance to authenticate.
Alternative to #597 as discussed in https://github.com/crim-ca/weaver/pull/597#discussion_r1480537709
Closes #597
> add SessionAuthHandler

- tests/functional/test_cli.py
- tests/functional/utils.py
- tests/utils.py
- Add stderr and stdout combined handling for cmd exec during tests 
- Handle recurring duplicate process name during tests between test cases
> fixes for test cli handling 

- .github/workflows/tests.yml
fix invalid reference in CI causing skip duplicate output to be misinterpreted (relates to https://github.com/fkirc/skip-duplicate-actions/issues/90)
> fix invalid reference in CI causing skip duplicate output to be misinterpreted 

- weaver/vault/views.py
relates to https://github.com/python/typeshed/issues/11663
> fix typing of `webob.compat` alias to `cgi.FieldStorage`

- .github/workflows/tests.yml
Add the `pip` CI cache option to avoid redownload of assets. 
If the target version for a package to install hits the cache, it will reduce the CI time. 
Since we leave many packages unpinned to get latest updates, it will not hit in many cases, but this is what we want.
> add CI python pip cache

- CHANGES.rst
- requirements.txt
relates to https://github.com/docker/docker-py/pull/3257, https://github.com/psf/requests/pull/6710, https://github.com/crim-ca/weaver/pull/651, https://github.com/crim-ca/weaver/pull/650
`docker-py` uses a custom adapter that does not override the new method used by `requests=2.32`
The `docker-py` PR is merged, but not released yet. 
Need to wait for a release to pin it.
> temporary pin `requests!=2.32` to avoid issue with `docker-py`

- requirements-doc.txt
pin `sphinx-argparse<0.5.0` to fix Sphinx/RTD docs build
relates to https://github.com/sphinx-doc/sphinx-argparse/issues/57
> pin sphinx-argparse<0.5.0 to fix Sphinx/RTD docs build

- requirements-sys.txt
fix invalid setup arguments encountered when versions missmtach between `setuptools` and `packaging`
> fix packaging/setuptools versions

- CHANGES.rst
- tests/test_formats.py
- weaver/formats.py
Recent (2024-09-93) PRs (#705, #706, etc.) have shown flaky CI testing results due to inconsistent SSL handshake errors from IANA. Avoid this extra validation to fail our pipelines, as they can generally be considered a safe URI location for this specific case.
> make CWL format check against IANA media-type URI more resilient against temporary/sporadic SSL handshake error

- CHANGES.rst
- docs/examples/jupyter_repo2cwl_python.py
- docs/source/conf.py
- docs/source/package.rst
- docs/source/references.rst
Add documentation about *Jupyter Notebook* to `CWL` conversion utility [`ipython2cwl`](https://github.com/common-workflow-lab/ipython2cwl) and a sample https://github.com/crim-ca/ncml2stac/tree/main#ncml-to-stac repository making use of it with the `Weaver` `CLI` to generate a deployed *OGC API - Processes* definition.
- Fixes [GD-247](https://crim-ca.atlassian.net/browse/GD-247)
- Fixes #63
> jupyter notebook to CWL docs

- CHANGES.rst
- docker/Dockerfile-base
- requirements.txt
- relates to https://github.com/celery/celery/issues/9254
- relates to https://jira.mongodb.org/browse/PYTHON-4756
> fix incompatibilities between extra requirements `celery[mongodb]` and `pymongo[srv]>=4.8.0`

- CHANGES.rst
- Makefile
- docs/source/package.rst
- tests/processes/test_wps_package.py
- tests/smoke/docker-compose.smoke-test.yml
- weaver/processes/wps_package.py
- weaver/typedefs.py
- weaver/wps_restapi/swagger_definitions.py
Changes
- Add parsing of additional metadata from schema.org in CWL document to convert into process fields
- fixes https://github.com/crim-ca/weaver/issues/463
- fixes https://github.com/crim-ca/weaver/issues/613
> Parsing cwl metadata

- docs/source/references.rst
- requirements-doc.txt
- relates to https://github.com/sphinx-doc/sphinx-argparse/issues/57
> allow `sphinx-argparse!=0.5.0` for latest fix 

- CHANGES.rst
- tests/functional/test_cli.py
- tests/utils.py
- weaver/cli.py
> CLI Job POST/PATCH operations for Part 4 Job Management

- CHANGES.rst
- docs/source/processes.rst
- tests/functional/test_wps_package.py
- tests/test_cli.py
- tests/wps_restapi/test_jobs.py
- tests/wps_restapi/test_processes.py
- weaver/cli.py
- weaver/processes/builtin/collection_processor.cwl
- weaver/processes/utils.py
- fix detection of `executionUnit` `href` using mapping representation 
- patch pytest markers with parametrized
- allow CLI override of `url` parameter on each operation
> Fix URL resolutions in various places

- CHANGES.rst
- docs/source/package.rst
- tests/processes/test_convert.py
- weaver/processes/convert.py
Given an input using: 
```json
{
"id": "test",
"schema": {
"type": "array",
"items": {
"type": "string",
"enum": ["value-1", "value-2"]
}
}
}
```
Automatically convert it in CWL as: 
```json
{
"id": "test",
"type": {
"type": "array",
"items": {
"type": "enum",
"symbols": ["value-1", "value-2"],
},
}
}
```
Previously, the definition was erroneously converted to the nested CWL enum by itself (without array representation).
> resolve OAS array with enum for OAP input directly specified

- .github/workflows/tests.yml
- attempt swap order of coverage actions
- relates to https://github.com/codecov/feedback/issues/304#issuecomment-2492675117
> explore fixes of coverage actions

- CHANGES.rst
- tests/processes/test_convert.py
- weaver/formats.py
- weaver/processes/convert.py
- relates to https://github.com/common-workflow-language/cwltool/issues/2071
- closes #763  
(alternative, simpler CWL without JS injection)
> add workaround patch of enum with colon failing CWL validation [URI variant]

- .github/workflows/zenodo.yml
- .zenodo.json
- CHANGES.rst
- CITATION.cff
- Makefile
- README.rst
- setup.cfg
Using the https://github.com/rseng/zenodo-release GitHub Action to purposely avoid using Zenodo's official integration that requires ornaization-level admin access to webhooks.
Add CITATIONS.cff and Zenodo metadata representations for convenience.
- based on changes in https://github.com/rseng/zenodo-release/pull/16
> setup zenodo and add citations

- CHANGES.rst
- tests/functional/test_cli.py
- tests/functional/test_job_provenance.py
- weaver/datatype.py
- weaver/wps_restapi/jobs/utils.py
> fix PROV endpoints returning invalid double Content-Type headers

- requirements.txt
Reverts crim-ca/weaver#792 as resolved by https://github.com/shapely/shapely/issues/2212
> Revert "patch fix against unresolved GEOS library by shapely "

- CHANGES.rst
- setup.cfg
- tests/functional/test_wps_app.py
- tests/functional/test_wps_package.py
- tests/functional/utils.py
- tests/wps_restapi/test_processes.py
- weaver/execute.py
- weaver/processes/execution.py
- weaver/store/base.py
- weaver/store/mongodb.py
- weaver/wps/service.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/jobs/utils.py
- handle WPS endpoint identifiers with `processID:revision` to allow describe/execution using older versions 
- fixes #799
- Add tests
> handle WPS endpoint identifiers with `processID:revision`

- docs/source/installation.rst
Provide guidance about more recent versions of MongoDB migration steps. 
This was already supported for a while, but wasn't explicitly mentioned in the docs. 
Operation updates insights from performing the steps on Hirondelle.
> Update installation.rst db-migration guide

- docs/source/conf.py
OGC Draft reports generation has been broken for a few weeks, and it is impossible to develop anything efficiently in the meantime since CI linkchecks breaks all the time. Patch-ignore it temporarily to allow other relevant checks to be evaluated.
- relates to https://github.com/opengeospatial/ogcapi-processes/issues/490
> temporarily ignore broken links from OGC Draft reports 

- Makefile
Error does not seem to be replicable locally, but happens sporadically during GitHub CI. 
Sometimes, retrying the execution simply works. 
The same script has been running for years, but recently started breaking on random occasion. 
Attempt to handle the case where the docker might not yet have finished booting with the previously used 10s delay, by dynamically retrying the request a few times. 
Only `test-docker` case is relevant here (doing a few runs for sanity check):
- using `curl` retries:
- https://github.com/crim-ca/weaver/actions/runs/14719312168/job/41309827916?pr=818 ❌ 
- https://github.com/crim-ca/weaver/actions/runs/14719312168/job/41310174866?pr=818 ❌ 
- https://github.com/crim-ca/weaver/actions/runs/14719312168/job/41310344216?pr=818 ❌ 
Even using `--retry-connrefused` …
> use retries to handle sporadic errors on CI docker still booting

- .github/workflows/tests.yml
- CHANGES.rst
- Makefile
- docker/Dockerfile-manager
- docker/Dockerfile-worker
In order to offer better traceability of the code and runtime environment (not just the underlying execution artifacts annotated by CWLProv / W3C PROV when running processing), annotate the provided docker image with best practice provenance details. 
Employ docker traceability attestations: 
- Provenance: https://docs.docker.com/build/metadata/attestations/slsa-provenance/
- Software bill-of-materials: https://docs.docker.com/build/metadata/attestations/sbom/
Requires an intermediate step to setup the `docker-container` driver as `builder`: 
https://docs.docker.com/build/builders/drivers/docker-container/
Allows a better [Docker Scout health score](https://docs.docker.com/scout/policy/) (other items remaining to iron out the score to be addressed in separate PRs). …
> PoC: add docker provenance & SBOM

- CHANGES.rst
- tests/wps_restapi/test_jobs.py
- weaver/base.py
- weaver/processes/constants.py
- weaver/status.py
- weaver/wps_restapi/jobs/jobs.py
- weaver/wps_restapi/jobs/utils.py
- weaver/wps_restapi/swagger_definitions.py
- Add ``f=xml`` support for `Job` status endpoints to directly retrieve the corresponding `WPS` `XML` status content.
- Add ``schema=wps`` and ``profile=wps`` query parameter support for `Job` status endpoints.
If used by themselves, these query parameter values will return the same `WPS` `XML` content as when using ``f=xml``.
If combined with `JSON` format (i.e.: ``?f=json&profile=wps``), the `OGC API - Processes` `Job` status information
will be returned instead, but using the corresponding `WPS` ``status`` values. Specifically, this allows returning
the previous `WPS`  ``succeeded`` and ``started`` status values instead of the `OGC API - Processes` ``successful``
and ``running`` values respectively. This is provided to help clients that have to deal with the mixture of
properties until …
> Support `f=xml` and `profile=wps` queries for job status

- CHANGES.rst
- Makefile
- docker/Dockerfile-base
- docker/Dockerfile-worker
- Remove additional software dependency in worker Docker image leading to outdated Python 3.11 and
its insecure dependencies to be installed along updated Python 3.12 with specific `Weaver` requirements.
- Reduce all Docker image sizes by approximately 1/3 with post-install removal of build dependencies.
> update dockers to remove outdated Python 3.11 packages and other build dependencies

- CHANGES.rst
- tests/wps_restapi/test_jobs.py
- weaver/wps_restapi/templates/responses/job_listing.mako
- weaver/wps_restapi/templates/responses/job_status.mako
- weaver/wps_restapi/templates/responses/util.mako
- Fix missing link in `Job` status `HTML` page for ``inputs`` and ``links`` references.
- Fix invalid link in `Job` status `HTML` page for ``logs`` reference.
- Fix consistency between link names between `Job` status and `Process` description `HTML` pages.
> fix multiple HTML paging links

- .github/workflows/tests.yml
- CHANGES.rst
- Makefile
- README.rst
- requirements-dev.txt
- setup.py
- Address issues flagged in https://github.com/crim-ca/weaver/actions/runs/15046776427/job/42293940240
- Add checks for generated PyPI dist to early-detect problem RST definitions
- Fix relevant RST issues for PyPI publish
- Relates to #828 
- Relates to #755
> remove auth override in CI for PyPI using trusted publishers

- .github/workflows/tests.yml
This reverts commit 21e0349780b5784830fbe6804fd7b87972df88bf.
The warning in https://github.com/crim-ca/weaver/actions/runs/15046776427/job/42293940240 suggested removing the token to employ PyPI trusted publisher feature. Doing simply breaks the operation (maybe because the project is not "created" yet?) https://github.com/crim-ca/weaver/actions/runs/15071189794/job/42369928796
``` 
Error: Trusted publishing exchange failure: 
Token request failed: the server refused the request for the following reasons:
* `invalid-publisher`: valid token, but no corresponding publisher (All lookup strategies exhausted)
```
> Revert "remove auth override in CI for PyPI using trusted publishers"
